name:                hsbin
version:             0.1.0.0
github:              "githubuser/hsbin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hsbin#readme>

dependencies:
- name: base 
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- name: relude
  mixin: 
    - (Relude as Prelude)
- fast-logger
- aeson
- servant
- servant-server
- hasql
- hasql-th
- hasql-pool
- hasql-migration
- tuple
- transformers
- warp
- http-types
- tuple
- exceptions
- unliftio-core
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsbin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsbin

tests:
  hsbin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsbin
